[package]
name = "rustchain"
version = "0.1.0"
authors = ["Marcin Skwarek <m.skwarek@stud.elka.pw.edu.pl>"]

[dependencies]
time = "0.1"
rust-crypto = "^0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rustc-serialize = "0.3.24"